apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app-of-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: app1
    server: https://kubernetes.default.svc
  source:
    path: argo-app
    repoURL: https://github.com/anilabha/argo-test2.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

